### ISSUE TITLE
How does this compare to Futures?

### ISSUE THREAD

**Issue by tejasmanohar** [Chymyst/chymyst-core#122]
It'd be good to add an example of how code using this paradigm compares to Futures (and Scala's ExecutionContext) in practice.

**Comment by winitzki** [comment]
I have written an essay about this. https://chymyst.github.io/chymyst-core/concurrency.html

**Comment by winitzki** [comment]
A non-technical version is here https://www.linkedin.com/pulse/choosing-concurrency-stack-sergei-winitzki
