### ISSUE TITLE
Terminology nitpick: recursive molecule ~> chain reaction?

### ISSUE THREAD

**Issue by naturallymitchell** [Chymyst/chymyst-core#153]
I'm just starting to study your work, so thank you for everything so far.  Thanks especially for focusing on making concurrency easier to understand, which I like coming from researching Akka as inspiration for Rust and then [Actix](https://github.com/fafhrd91/actix).  To start, I've been trying to sort out how the families of conceptual models relate to one another and to see if some metaphor could help for terminologically organizing their features.  I also just so happened to want a declarative scripting language built on top, so this project is a great find.  :)

My question is, what do you think about calling [MergeSort's reaction](https://github.com/Chymyst/chymyst-core/blob/f07d72e7d1ccf15ceadb0555d7ec46269226146e/benchmark/src/main/scala/io/chymyst/benchmark/MergeSort.scala#L46) a [chain reaction](https://en.wikipedia.org/wiki/Chain_reaction) instead of a `recursive molecule`?  Hopefully it would help to gain further insight about how these types of "chemical reactions" are set up and generally flow, and it would retain the metaphor which hides the internals.

Aside:  I'm curious to see if another metaphor would work, either (possibly delegation-based) teamwork or supply chain logistics, so you can see my very rough first attempt with those terms in https://github.com/fafhrd91/actix/issues/9.  I don't know Actix' semantics for "chain reactions" but it would be very interesting to compare for these discussions.

**Comment by winitzki** [comment]
"Chain reaction" sounds interesting, I'll think about revising the explanation.
